### ISSUE TITLE
Compile error: failed to compile target: busybox

### ISSUE THREAD

**Issue by retr0h** [deepmind/kapitan#641]
**Describe the bug/feature**

Error working through examples

**To Reproduce**
1. Git clone repo
2. cd examples/kubernetes
3. kapitan compile

**Expected behavior**

Examples used in [docs](https://kapitan.dev/#quickstart) should work

**Screenshots**

```
~/git/kapitan/examples/kubernetes master
.venv ❯ kapitan compile
Compiled removal (0.00s)


Jsonnet error: failed to compile /Users/john.dewey/git/kapitan/examples/kubernetes/components/namespace/main.jsonnet:
 RUNTIME ERROR: 'NoneType' object has no attribute 'inventory_path'
        /Users/john.dewey/git/kapitan/.venv/lib/python3.8/site-packages/kapitan/lib/kapitan.libjsonnet:9:59-100 function <anonymous>
        /Users/john.dewey/git/kapitan/examples/kubernetes/components/namespace/main.jsonnet:3:19-34     thunk <inventory>
        /Users/john.dewey/git/kapitan/examples/kubernetes/components/namespace/main.jsonnet:4:11-20     thunk <p>
        /Users/john.dewey/git/kapitan/examples/kubernetes/components/namespace/main.jsonnet:7:36        thunk <name>
        /Users/john.dewey/git/kapitan/examples/kubernetes/lib/kube.libjsonnet:463:49-53 thunk <name>
        /Users/john.dewey/git/kapitan/examples/kubernetes/lib/kube.libjsonnet:52:23-27  object <anonymous>
        /Users/john.dewey/git/kapitan/examples/kubernetes/lib/kube.libjsonnet:52:15-29  object <anonymous>
        /Users/john.dewey/git/kapitan/examples/kubernetes/lib/kube.libjsonnet:(50:15)-(55:6)    object <anonymous>
        /Users/john.dewey/git/kapitan/examples/kubernetes/components/namespace/main.jsonnet:7:21-48     object <anonymous>
        During manifestation

Compile error: failed to compile target: busybox

~/git/kapitan/examples/kubernetes master
.venv ❯ kapitan --version
0.29.3

```

** If it's a bug (please complete the following information):**
 - `python --version`:
Python 3.8.5
 - `pip3 --version`: 
pip 20.1.1 from /Users/john.dewey/git/kapitan/.venv/lib/python3.8/site-packages/pip (python 3.8)
 - `Are you using pyenv or virtualenv?`
pyenv

**Comment by retr0h** [comment]
Oddly works just fine if I use the docker container.

```
~/git/kapitan/examples/kubernetes master 12s
.venv ❯ docker run -t --rm -v $(pwd):/src:delegated deepmind/kapitan compile
Compiled busybox (0.32s)
Compiled labels (0.33s)
Compiled minikube-nginx-jsonnet (0.22s)
Compiled minikube-nginx-kadet (0.13s)
Compiled removal (0.01s)
Compiled minikube-mysql (0.40s)
Compiled minikube-es (0.98s)
Compiled all-glob (1.27s)
```

**Comment by ramaro** [comment]
Thanks for reporting @retr0h 
How did you install kapitan? Using pip or straight from master?

**Comment by retr0h** [comment]
>  How did you install kapitan? Using pip or straight from master?

Pip

**Comment by Roman-Clumio** [comment]
I'm getting the same error straight from master.
Here's how to reproduce:
```
$ git clone https://github.com/deepmind/kapitan.git
$ cd kapitan
$ virtualenv venv
created virtual environment CPython3.8.6.final.0-64 in 443ms

$ source venv/bin/activate
$ pip install -r requirements.txt
$ git submodule update --init
Submodule 'kapitan/reclass' (https://github.com/kapicorp/reclass.git) registered for path 'kapitan/reclass'

$ cd examples/docker/
$ ../../bin/kapitan compile

Jsonnet error: failed to compile /Users/roman/temp/repos/kapitan/examples/docker/components/jsonnet/jsonnet.jsonnet:
 RUNTIME ERROR: 'NoneType' object has no attribute 'inventory_path'
	/Users/roman/temp/repos/kapitan/kapitan/lib/kapitan.libjsonnet:9:59-100	function <anonymous>
	/Users/roman/temp/repos/kapitan/examples/docker/components/jsonnet/jsonnet.jsonnet:2:19-34	thunk <inventory>
	/Users/roman/temp/repos/kapitan/examples/docker/components/jsonnet/jsonnet.jsonnet:6:15-24	thunk <a>
	/Users/roman/temp/repos/kapitan/examples/docker/components/jsonnet/jsonnet.jsonnet:(4:1)-(7:2)	function <anonymous>
	/Users/roman/temp/repos/kapitan/examples/docker/components/jsonnet/jsonnet.jsonnet:(4:1)-(7:2)

Compile error: failed to compile target: docker
```

**Comment by roman8422** [comment]
I'm getting the same error straight from master.
Here are steps to reproduce:
```
$ git clone https://github.com/deepmind/kapitan.git
$ cd kapitan
$ virtualenv venv
created virtual environment CPython3.8.6.final.0-64 in 443ms

$ source venv/bin/activate
$ pip install -r requirements.txt
$ git submodule update --init
Submodule 'kapitan/reclass' (https://github.com/kapicorp/reclass.git) registered for path 'kapitan/reclass'

$ cd examples/docker/
$ ../../bin/kapitan compile

Jsonnet error: failed to compile /Users/roman/temp/repos/kapitan/examples/docker/components/jsonnet/jsonnet.jsonnet:
 RUNTIME ERROR: 'NoneType' object has no attribute 'inventory_path'
	/Users/roman/temp/repos/kapitan/kapitan/lib/kapitan.libjsonnet:9:59-100	function <anonymous>
	/Users/roman/temp/repos/kapitan/examples/docker/components/jsonnet/jsonnet.jsonnet:2:19-34	thunk <inventory>
	/Users/roman/temp/repos/kapitan/examples/docker/components/jsonnet/jsonnet.jsonnet:6:15-24	thunk <a>
	/Users/roman/temp/repos/kapitan/examples/docker/components/jsonnet/jsonnet.jsonnet:(4:1)-(7:2)	function <anonymous>
	/Users/roman/temp/repos/kapitan/examples/docker/components/jsonnet/jsonnet.jsonnet:(4:1)-(7:2)

Compile error: failed to compile target: docker
```

**Comment by roman8422** [comment]
compile works in version 0.29.2 and is broken in 0.29.3 and 0.29.4

**Comment by roman8422** [comment]
Works for me again. Was fixed in 6d8c91c.
